name: Update WrapDB

on: workflow_dispatch

jobs:
  generate_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: python3 -u wrapdb.py ${{ github.repository }} ${{ secrets.GITHUB_TOKEN }}